app:
  name: "chiwen_server"
  mode: "debug"
  listen: "8090"
  aoto_migrate: true

server:
  host: "0.0.0.0"
  external_url: "http://localhost:8090"

log:
  level: "debug"
  filename: ""
  max_size: 200
  max_age: 7
  max_backups: 3

mysql:
  host: "192.168.19.100"  # MySQL服务器地址（根据实际部署环境修改）
  port: 3306
  user: "myuser"
  password: "MyUserP@ss123"
  dbname: "myapp"
  max_open_connes: 200
  max_idle_connes: 50
