app:
  name: "chiwen_server"
  mode: "release"
  # mode: "test"
  # mode: "debug"
  listen: "8090"
  # 自动创建制定模型等数据库表结构 不会更新已存在的数据库表
  aoto_migrate: true

server:
  host: "192.168.19.100"     # 或者内网IP: 10.0.0.8
  external_url: "wss://jump.yourdomain.com"  # 强烈建议配这个！前端必须能访问

# 如果是用 Nginx 反代，记得配置 WebSocket 支持：
#location /api/v1/tty/ws {
#    proxy_pass http://127.0.0.1:8090;
#    proxy_http_version 1.1;
#    proxy_set_header Upgrade $http_upgrade;
#    proxy_set_header Connection "upgrade";
#}

log:
  level: "debug"
  filename: ""
  max_size: 200
  max_age: 7
  max_backups: 3

mysql:
  host: "192.168.19.100"
  port: 3306
  user: "myuser"
  password: "MyUserP@ss123"
  dbname: "myapp"
  max_open_connes: 200
  max_idle_connes: 50
